### ISSUE TITLE
"Run local server to /output directory" did not work

### ISSUE THREAD

**Issue by sustmi** [TomasVotruba/shopsys-spryker-and-sylius-analysis#1]
Command `php -S localhost:8001 -t output` (as written in README.md) did not work properly.

I had to run:
```
php -S localhost:8001 -t output/shopsys/php-metrics/
php -S localhost:8001 -t output/shopsys/php-metrics/
```
otherwise the the page was loaded without JS and CSS.

**Comment by TomasVotruba** [comment]
Dropped as too non-flexible solution.

Output will be in private Docs, where we can better describe particular results.
