### ISSUE TITLE
Composer "complete" fails on "cpd"

### ISSUE THREAD

**Issue by sustmi** [TomasVotruba/shopsys-spryker-and-sylius-analysis#2]
When running "composer complete" as stated in README.md, copy-paste detector finds some violations and therefore "composer complete" exits and fails to run other tools ("dep" and "met").

**Comment by TomasVotruba** [comment]
Thanks for report. Suggested workaround is ` | true`

**Comment by TomasVotruba** [comment]
Resolved by `| true`
